on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d   #v5.1.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: ruff
      run: poetry run ruff check --output-format=github .
    - name: black
      run: poetry run black --check .
    - name: isort
      run: poetry run isort --check .
    - name: mypy
      run: poetry run mypy .
