on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: test
      run: |
        poetry run pytest --doctest-modules --junitxml=junit/test-results.xml
